name: Lighthouse Check

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build and start the project
        run: |
          npm run build
          nohup npm start > server.log 2>&1 &

      - name: Wait for the application to start
        run: |
          echo "Aguardando o servidor..."
          npx wait-on http://localhost:5173 --timeout 30000

      # Correção do Erro: Adiciona os argumentos necessários para o Lighthouse rodar no Linux do GitHub
      - name: Run Lighthouse CI
        run: npm run lighthouse-ci
        env:
          LHCI_CHROME_FLAGS: "--no-sandbox --headless --disable-gpu"
